# Generated by Django 4.2.24 on 2025-09-16 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('vitamin_d_iu', models.FloatField(help_text='IU per 100g/serving')),
                ('is_vegetarian', models.BooleanField(default=False)),
                ('is_lactose_free', models.BooleanField(default=False)),
                ('is_nut_free', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='NutritionTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('tip_text', models.TextField()),
                ('expanded_text', models.TextField(blank=True)),
                ('related_foods', models.ManyToManyField(blank=True, to='nutrition.fooditem')),
            ],
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=16)),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], max_length=16)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrition.fooditem')),
            ],
        ),
    ]
