# Generated by Django 5.2.5 on 2025-09-04 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitamin_d_helper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='country',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, default='Melbourne', max_length=100),
        ),
    ]
