# Generated by Django 4.2.24 on 2025-10-08 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vitamin_d_helper', '0002_remove_userprofile_country_alter_userprofile_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outdoor_time', models.CharField(max_length=50)),
                ('work_pattern', models.CharField(max_length=50)),
                ('skin_type', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('clothing_coverage', models.CharField(max_length=50)),
                ('vitamin_d_supplement', models.CharField(max_length=50)),
                ('vitamin_d_foods', models.CharField(max_length=50)),
                ('risk_score', models.IntegerField()),
                ('result', models.CharField(max_length=20)),
                ('uv_index', models.FloatField(default=0)),
                ('weekly_plan', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
