# Generated by Django 4.2.24 on 2025-10-08 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitamin_d_helper', '0003_questionnaireresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaireresponse',
            name='user_uuid',
            field=models.UUIDField(null=True),
        ),
    ]
