# Generated by Django 4.2.24 on 2025-09-17 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factoid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('text', models.TextField()),
                ('badge', models.CharField(blank=True, default='', max_length=32)),
                ('source_name', models.CharField(blank=True, default='', max_length=120)),
                ('source_url', models.URLField(blank=True, default='')),
                ('icon', models.CharField(blank=True, default='', max_length=64)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order_index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LifestyleTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('impact', models.CharField(choices=[('beneficial', 'Beneficial'), ('concerning', 'Concerning')], max_length=16)),
                ('front_summary', models.CharField(max_length=140)),
                ('back_detail', models.TextField()),
                ('icon', models.CharField(blank=True, default='', max_length=64)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order_index', 'id'],
            },
        ),
    ]
