# Generated by Django 5.2.5 on 2025-09-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_scraper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuratedArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(blank=True, max_length=120)),
                ('image_url', models.URLField(blank=True)),
                ('url', models.URLField(help_text='External article URL')),
                ('source', models.CharField(help_text='Publisher (e.g., UniSA, ABS, SBS)', max_length=120)),
                ('date_published', models.DateTimeField()),
            ],
            options={
                'ordering': ['-date_published'],
            },
        ),
    ]
