# Generated by Django 5.2.5 on 2025-08-27 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500, unique=True)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('source_domain', models.CharField(max_length=100)),
                ('content', models.TextField(blank=True)),
                ('keywords_found', models.CharField(blank=True, max_length=200)),
                ('date_published', models.DateTimeField(blank=True, null=True)),
                ('date_collected', models.DateTimeField(auto_now_add=True)),
                ('has_keywords', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-date_collected'],
            },
        ),
    ]
